import pygame

ROWS, COLS = 8, 8 # rows and columns
SQUARE_SIZE = 90 # square size -> to change window size: change square size

# board size according to the squares
WIDTH = SQUARE_SIZE * COLS
HEIGHT = SQUARE_SIZE * ROWS

# piece sizes
SIZE_BIG = 0.9
SIZE_MEDIUM = 0.8
SIZE_SMALL = 0.6
SIZE_SMALLER = 0.4

# colors in rgb
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREY = (128, 128, 128)
LIGHT_GREY = (211, 211, 211)
PINK = (255, 105, 180)
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0)

# Color pattern of the board
COLOR_PATTERN = [
    [GREY, LIGHT_GREY, GREY, LIGHT_GREY, GREY, LIGHT_GREY, GREY, LIGHT_GREY],
    [LIGHT_GREY, LIGHT_GREY, GREY, LIGHT_GREY, GREY, LIGHT_GREY, GREY, GREY],
    [GREY, GREY, GREY, LIGHT_GREY, GREY, LIGHT_GREY, LIGHT_GREY, LIGHT_GREY],
    [LIGHT_GREY, LIGHT_GREY, LIGHT_GREY, LIGHT_GREY, GREY, GREY, GREY, GREY],
    [GREY, GREY, GREY, GREY, LIGHT_GREY, LIGHT_GREY, LIGHT_GREY, LIGHT_GREY],
    [LIGHT_GREY, LIGHT_GREY, LIGHT_GREY, GREY, LIGHT_GREY, GREY, GREY, GREY],
    [GREY, GREY, LIGHT_GREY, GREY, LIGHT_GREY, GREY, LIGHT_GREY, LIGHT_GREY],
    [LIGHT_GREY, GREY, LIGHT_GREY, GREY, LIGHT_GREY, GREY, LIGHT_GREY, GREY]
]
